### ISSUE TITLE
朗读异常

### ISSUE THREAD

**Issue by duty9527** [byzze/handy-translate#6]
https://github.com/byzze/handy-translate/blob/e6a2aaa5fa82c929e0cd8e091195e97323fe6dc2/frontend/src/window/Translate/components/TargetArea/index.jsx#L354C33-L354C33

代码中此处应该缺少了 _Spinner_ 组件的引入，导致点击朗读之后页面会加载失败，然后变成白色

**Comment by byzze** [comment]
方便描述一下触发的操作以及出问题界面截图吗？

**Comment by blue-duty** [comment]
翻译后点击朗读按钮，直接变白， 原因应该是我提供的链接位置的组件没有引入导致的

**Comment by byzze** [comment]
明白了，已更新代码，后面更新一下安装包，感谢提醒😊
